--- 
contact: 
  email: gabriel.chaney@gmail.com
  phone: 602-332-3761
  website: https://gabrielchaney.com
education: 
  degree: BS E.
  history: 
    - 
      institution: Arizona State University
      title: BS E, Computer Systems Engineering
      url: https://www.asu.edu
  level: degree
  summary: ~
employment:
  history:
    -
      employer: Package Portal Inc.
      url: https://www.packageportal.com/
      position: Co-founder, CTO
      start: 2019-06
      summary: 'Package Portal provides Web3 cryptocurrency incentives for user feedback. Co-founding this company was achieving one of my long-term goals.'
      highlights:
        - Learned React Native, Hasura GraphQL, and Firebase authentication to build my first native app
        - Recruited small team of founding engineers
        - Set the tone for architecture and API and pub/sub governance
        - Coordinated the creation of our initial branding, logo, and UX flows with UX designers
        - Established pipeline of engineering contractor for building integration tests and internal libraries
        - "Set-up company IT infrastructure: GSuite, Rippling, Slack, authentication, and cloud hosting"
    - 
      employer: Philips
      url: https://www.usa.philips.com/
      position: Lead Engineer
      start: 2020-01
      end: 2021-6
      summary: Philips is a multinational health care company. Our group's focus was to continue the patient instruction product Medumo was acquired for.
      highlights:
        - Guided team through updating our legacy systems to scale with increased number of patients
        - Built strong working relationships with new hires continuing to leverage my mentoring skills but with more of a product and vision focus
        - Promoted product vision for a new API that managed SMS sending and consent as a potential internal SaaS product including a mention in a Twilio blog post
        - Drove cross-functional collaboration for a potential new cardiology business opportunity within the Philips product ecosystem
    - 
      employer: Medumo
      url: https://www.medumo.com/
      position: Senior Software Engineer
      start: 2018-03
      end: 2019-12
      summary: Medumo was a health tech company focused on helped healthcare organizations send instructions to patients using SMS, email, snail mail, etc.
      highlights:
        - Drove microservice development across the team through patterns and technology from message bus for communication to Terraform modules for re-useable infrastructure creation
        - Filled gaps in process from branching strategies (e.g. gitflow) to documentation (e.g. repo readme's, plantUML) to improved CI/CD definitions (e.g. pipeline yaml over UI)
        - Refactored the core patient enrollment script-like procedure into a resuable, testable library
        - Built HIPAA-compliant integrations with the medical record systems including Epic with multiple hospitals receiving millions of messages from these hospitals
        - Guided a newer engineer through designing and excuting a message broadcast tool that became one of our most popular tools with clients
        - Mentored an amazing group of newer engineers using paired programming to code reviews to a weekly Design Day meeting
    - 
      employer: HomeLight
      url: https://www.homelight.com/
      position: Software Engineer
      start: 2018-01
      end: 2018-03
      summary: HomeLight automates connecting real estate agents with home sellers. This was a transitional period for me leaving my first acquisition experience. I arrived right after a Series A round and realized that I wanted another early-stage startup experience to practice all I had learned.
    - 
      employer: RetailMeNot
      url: https://retailmenot.com
      position: Engineering Manager
      start: 2016-08
      start: 2017-12
      summary: RetailMeNot provides multiple ways to save consumer on retail purchases from gift cards to coupons. I had the privilege of empowering a growing number of engineers in a new office through many technical and cultural changes. I also helped lead the team to ship APIs and products critical in the first year of acquisition.
      highlights:
        - Played a pivotal role in doubling the total team size in the first year of acquisition
        - Designed and shipped an alpha and private beta of a new mobile product
        - Created plan to deliver first Phoenix/Elixir API and drove plan to completion
        - Organized the team to decide on tech for a mobile app which resulted in a working prototype of a React Native Android app in a week
        - Counseled a lead engineer through rallying a team to tackle some significant scaling issues
        - Guided team through acquisition changes
      keywords:
        - Scrum
        - Ruby on Rails
        - Heroku
        - PostgreSQL
        - RabbitMQ
        - Redis
        - NewRelic
        - Microservices
        - Sentry
        - Papertrail
        - Swift
        - Bitrise
        - React Native
        - Phoenix/Elixir
    - 
      employer: RetailMeNot
      url: https://retailmenot.com
      position: Senior Software Engineer
      start: 2016-04
      end: 2016-08
      summary: This was a transitional post-acquisition position as the company calibrated to the existing team and the business direction.
      highlights:
        - Organized engineering group into 3 teams
        - Led teams to adopt Scrum with great success
        - Delivered initial UI that denoted acquisition
        - Worked with teams in Austin to develop initial post-acquisition roadmap
      keywords:
        - Scrum
        - Ruby on Rails
        - Heroku
        - PostgreSQL
        - RabbitMQ
        - Redis
        - NewRelic
        - Microservices
        - Sentry
        - Papertrail
    - 
      employer: Giftcard Zen
      url: https://giftcardzen.com
      position: Lead Developer
      start: 2014-04
      end: 2016-04
      summary: I transitioned from years of experience in a .NET enterprise environment to a Rails startup environment. I was able to apply many design principles I learned at NCARB (DDD, distributed system design, etc.) to guide a small team towards a microservices architecture and a continuous delivery pipeline. We were able to ship the features, survive the DDoS attacks, and be a fun united team to be acquired by RetailMenot in April 2016.
      highlights:
        - Built the foundation for the continuous integration and delivery pipeline
        - Shepherded architecture from monoliths towards microservices
        - Drove use of pub/sub including initiating an in-house developed open source project foundational in our architecture
        - Helped develop a scaleable interview process to build the core team        
        - Developed and presented technical documentation for the RetailMeNot acquisition due-diligence team including their CTO
      keywords:
        - Ruby on Rails
        - Angular.js
        - Heroku
        - PostgreSQL
        - RabbitMQ
        - Redis
        - NewRelic
        - Microservices
        - Sentry
        - Papertrail
    - 
      employer: InfernoRed Technology
      url: http://www.infernored.com/
      position: Software Engineer
      start: 2014-04
      end: 2013-06
      summary: InfernoRed is a software consutlant shop. I helped a new consulting firm build and improve software for their clients. I played a key role in answering client performance questions about their SaaS web application as well as contributed to web and mobile applications.
      highlights:
        - Built a heavliy customized load test suite for testing a multi-tenant app
        - Presented performance analysis and recommendations to the client VP and leads
        - Contributed to development efforts on a Windows Store app
      keywords:
        - C#
        - ASP.NET MVC
        - Entity Framework Code-First
        - Visual Studio
    - 
      employer: National Council of Architectural Registration Boards
      position: Software Engineer
      start: 2011-02
      end: 2013-06
      summary: I joined a newly formed team to upgrade this not-for-profit's legacy .NET applications to next-gen .NET applications. This is where I was introduced to methodologies like Scrum, Domain-Driven Design and distributed systems design. I took classes from Eric Evans (Domain-Driven Design author) and Udi Dahan (NServiceBus author).
      url: https://www.ncarb.org/
      highlights:
        - Built JavaScript and CSS infrastructure for the new flagship web application
        - Facilitated collaboration between between third-party UX team and the development team
        - Promoted the use of Backbone.js to the development team
        - Recommend a better solution for the new evaluation report which resulted in a different feature roadmap
      keywords:
        - C#
        - Visual Studio
        - Backbone.js
        - ASP.NET MVC
        - SQL Server
        - Service Oriented Architecture
        - Distributed transactions
        - Publish / subscribe
    - 
      employer: Lockheed Martin
      url: https://www.lockheedmartin.com
      position: Software Engineer
      start: 2011-02
      end: 2007-08
      summary: I delivered my first production applications that included object-oriented designs, jQuery, ORM, and HTTP API calls.
      highlights:
        - Championed jQuery to the team to meet a customer request for web UI performance improvements
        - Added client web service requests to external systems which decreased HR analyst processing time from three weeks to just over one week
        - Drove changes to replace the use of stored procedures with ORM
        - Integrated with a Netconf API to configure Cisco routers
      keywords:
        - C#
        - Visual Studio
        - ASP.NET WebForms
        - jQuery
        - HTML/CSS
        - Fluent NHibernate
        - SQL Server
        - Oracle
        - Java
    - 
      employer: Harmony House
      position: Web Developer/Salesman
      start: 2007-08
      end: 1999-03
      summary: This is where I built my first web application while I was working on my CS degree (awww). I introduced myself to CSS, HTML, PHP, and MVC through this creative process. I had so much fun learning and building.
      highlights:
        - Set-up local area network and point-of-sale system
        - Built store website including a custom content management system increasing piano sales by 48%
        - Sold guitars
      keywords:
        - PHP
        - MVC
        - MySQL
        - HTML/CSS
  summary: 10+ years software development experience.
info: 
  brief: "With over a decade of software engineering experience from enterprise to startups, leading teams to shipping code, joining companies to founding them, Gabe's journey and relationships have shaped him to lead humans that build software products for humans. Gabe has a strong focus on mentorship, product, and architecture."
  characterClass: Programmer
  label: Software Engineer & Leader
location: 
  city: Phoenix
  country: US
  region: AZ
meta: 
  format: FRESH@0.6.0
  version: 0.4.0
name: Gabriel Chaney
social: 
  - 
    label: github
    network: GitHub
    url: https://github.com/gabrieljoelc
    user: gabrieljoelc
  - 
    label: linkedin
    network: LinkedIn
    url: https://www.linkedin.com/in/gabrielchaney
  - 
    label: twitter
    network: Twitter
    url: https://twitter.com/gabrieljoelc
    user: gabrieljoelc
