# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: gabrieljoelc/fresh-themes
        path: fresh-themes
    - uses: sjdonado/heroku@master
    - uses: mikeal/npx@1.0.0
    - name: Generate FRESH JSON from YAML
      run: ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < default.yml > default.json
    - name: Generate FRESH HTML from JSON using fresh-themes
      run: npx hackmyresume BUILD default.json TO out/index.html -t fresh-themes/themes/jae
    - name: Prepare Heroku static site
      run: |
        ls -al
        cd out
        # fake Heroku out to run static website http://blog.teamtreehouse.com/deploy-static-site-heroku
        echo "<?php header( 'Location: /index.html' ) ;  ?>" > index.php
        git init
        git config --global user.email "gabriel.chaney@gmail.com"
        git config --global user.name "Gabriel Chaney"
        git add .
        git commit -m "Prepare Heroku deployment"
    - name: Deploy to Heroku
      working-directory: out
      run: |
        heroku git:remote -agabrielchaney-static-site -r heroku_gabrielchaney-static-site --ssh-git
        git push heroku_gabrielchaney-static-site refs/heads/master -f
    - name: Check that website responds
      run: curl http://www.gabrielchaney.com/ --retry 3
