# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/heroku@1.0.0
    - uses: actions/setup-ruby@v1.0.0
    - name: Build and deploy resume to Heroku
      run: |
        ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < default.yml > default.json
        echo test, and deploy your project.
        git clone git@github.com:gabrieljoelc/fresh-themes.git
        npm install hackmyresume -g
        hackmyresume BUILD default.json TO out/index.html -t fresh-themes/themes/jae
        # fake Heroku out to run static website http://blog.teamtreehouse.com/deploy-static-site-heroku
        echo "<?php header( 'Location: /index.html' ) ;  ?>" > out/index.php
        cd out
        git init
        git config --global user.email "gabriel.chaney@gmail.com"
        git config --global user.name "Gabriel Chaney"
        git add .
        git commit -m "Prepare Heroku deployment"
        heroku git:remote -agabrielchaney-static-site -r heroku_gabrielchaney-static-site --ssh-git
        git push heroku_gabrielchaney-static-site refs/heads/master -f
        curl http://www.gabrielchaney.com/ --retry 3
        cd ~/
