# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
env:
  ARTIFACT_NAME: herokuStaticSite
  PROCESS_DIR: ${{ env.HOME }}/tmp
  THEMES_DIR: ${{ env.PROCESS_DIR }}/fresh-themes
  CUSTOM_THEMES_DIR: ${{ env.THEMES_DIR }}/themes/jae
  SRC_DIR: ${{ env.GITHUB_WORKSPACE }}/src
  OUTPUT_DIR: ${{ env.HOME }}/dist

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - ci-update/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: gabrieljoelc/fresh-themes
        path: fresh-themes
    - uses: mikeal/npx@1.0.0
    - name: Generate FRESH JSON from YAML
      working_directory: ${{ env.SRC_DIR }}
      run: ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < default.yml > $PROCESS_DIR/default.json
    - name: Generate FRESH HTML from JSON using fresh-themes
      working_directory: ${{ env.PROCESS_DIR }}
      run: npx hackmyresume BUILD default.json TO $OUTPUT_DIR/index.html -t $CUSTOM_THEMES_DIR
    - name: Prepare Heroku static site
      working-directory: ${{ env.OUTPUT_DIR }}
      run: |
        # fake Heroku out to run static website http://blog.teamtreehouse.com/deploy-static-site-heroku
        echo "<?php header( 'Location: /index.html' ) ;  ?>" > index.php
        git init
        git config --global user.email "gabriel.chaney@gmail.com"
        git config --global user.name "Gabriel Chaney"
        git add .
        git commit -m "Prepare Heroku deployment"
    - name: Upload Heroku static site repo to artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.OUTPUT_DIR }}
  deployHeroku:
    env:
      SITE_DOMAIN: http://www.gabrielchaney.com/
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: sjdonado/heroku@master
    - name: Heroku static site repo from artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
    - name: Create .netrc for Heroku login
      run: |+
        cat >~/.netrc <<EOF
        machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    - name: Add Heroku remote to temp repo
      working-directory: ${{ env.ARTIFACT_NAME }}
      run: |
        heroku git:remote --app $HEROKU_APP
      env:
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Git push to Heroku
      working-directory: ${{ env.ARTIFACT_NAME }}
      run: |
        git push heroku refs/heads/master -f
    - name: Check that website responds
      run: curl $SITE_DOMAIN --retry 3
