# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the main branch
env:
  ARTIFACT_NAME: herokuStaticSite

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - ci-update/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      SRC_DIR: ${{ github.workspace }}/src
      PROCESS_DIR: ${{ github.workspace }}/tmp
      CUSTOM_THEMES_DIR: ${{ github.workspace }}/fresh-themes/themes/jae
      OUTPUT_DIR: ${{ github.workspace }}/dist

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: gabrieljoelc/fresh-themes
        path: fresh-themes
    - uses: mikeal/npx@1.0.0
    - name: Generate FRESH JSON from YAML
      working-directory: ${{ env.SRC_DIR }}
      run: |
        ls -al
        mkdir $PROCESS_DIR
        ls -al
        ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < default.yml > $PROCESS_DIR/default.json
    - name: Generate FRESH HTML from JSON using fresh-themes
      working-directory: ${{ env.PROCESS_DIR }}
      run: |
        ls -al
        mkdir $OUTPUT_DIR
        ls -al
        npx hackmyresume BUILD default.json TO $OUTPUT_DIR/index.html -t $CUSTOM_THEMES_DIR
    - name: Prepare Heroku static site
      working-directory: ${{ env.OUTPUT_DIR }}
      run: |
        # fake Heroku out to run static website http://blog.teamtreehouse.com/deploy-static-site-heroku
        echo "<?php header( 'Location: /index.html' ) ;  ?>" > index.php
        git init
        git config --global user.email "gabriel.chaney@gmail.com"
        git config --global user.name "Gabriel Chaney"
        git add .
        git commit -m "Prepare Heroku deployment"
    - name: Upload Heroku static site repo to artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.OUTPUT_DIR }}
  deployHeroku:
    env:
      SITE_DOMAIN: http://www.gabrielchaney.com/
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
      APP_HEALTH: "https://${{ secrets.HEROKU_APP }}.herokuapp.com/health"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download static site repo from artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
    - name: Heroku login
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ env.HEROKU_APP }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        justlogin: true
    - run: heroku login
    - name: Add Heroku remote to temp repo
      working-directory: ${{ env.ARTIFACT_NAME }}
      run: |
        heroku git:remote --app $HEROKU_APP
    - name: Git push to Heroku
      working-directory: ${{ env.ARTIFACT_NAME }}
      run: |
        git push heroku refs/heads/master -f
    - name: Check that website responds
      run: curl $SITE_DOMAIN --retry 3
